services:
  backend:
    container_name: backend_usuarios
    image: ${DOCKER_IMAGE_URL:-back_eval2-backend:latest}
    build: .
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - "${PORT}:3000"
